
import pygame as pg
import math
import sys
from data.constants import RARITY_ORDER, ATTACK_ANIM_DURATION, HIT_ANIM_DURATION, HEAL_ANIM_DURATION, CAST_ANIM_DURATION, DEATH_ANIM_DURATION, MAX_ITEMS_EQUIPPED

# Display
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60
FONT_NAME = None # Default font
FONT_SIZE = 18
SMALL_FONT_SIZE = 14
LARGE_FONT_SIZE = 24
MENU_FONT_SIZE = 48

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (150, 150, 150)
LIGHT_GRAY = (200, 200, 200)
DARK_GRAY = (50, 50, 50)
GOLD = (255, 215, 0)
RED = (200, 0, 0)
GREEN = (0, 200, 0)
BLUE = (0, 0, 200)
CYAN = (0, 200, 200)
MAGENTA = (200, 0, 200)
YELLOW = (200, 200, 0)
PANEL_BG = (30, 30, 40)
BUTTON_BG = (70, 70, 90)
BUTTON_HOVER = (100, 100, 120)
HIGHLIGHT_COLOR = (255, 255, 100) # Renamed from HIGHLIGHT
INACTIVE_SYNERGY = (100, 100, 100)
ACTIVE_SYNERGY_BRONZE = (180, 110, 0)
ACTIVE_SYNERGY_SILVER = (192, 192, 192)
ACTIVE_SYNERGY_GOLD = GOLD
HEALTH_BAR_BG = (50, 50, 50)
HEALTH_BAR_COLOR = (0, 220, 0)
ENEMY_COLOR = (220, 50, 50)
ALLY_COLOR = BLUE # For engine mapping
MAP_NODE_BG = (60, 60, 80)
MAP_NODE_CURRENT = (100, 200, 100)
MAP_NODE_VISITED = (40, 40, 50)
MAP_PATH = (80, 80, 100)
ITEM_COLOR = (100, 50, 150)
DAMAGE_PHYSICAL_COLOR = (255, 100, 0)
DAMAGE_MAGIC_COLOR = (100, 100, 255)
DAMAGE_TRUE_COLOR = WHITE
HEAL_COLOR = GREEN
BUFF_COLOR = CYAN
OVERTIME_COLOR = (255, 0, 255)
HIT_FLASH_COLOR = WHITE
HEAL_FLASH_COLOR = (100, 255, 100)
CAST_FLASH_COLOR = (100, 200, 255)
DEATH_COLOR = (80, 20, 20)
PROJECTILE_BASIC_COLOR = YELLOW
PROJECTILE_MAGIC_COLOR = MAGENTA
SLASH_COLOR = WHITE
HIT_SPARK_COLOR = (255, 200, 0)

RARITY_COLORS = {'COMMON': GRAY, 'UNCOMMON': GREEN, 'RARE': BLUE, 'EPIC': MAGENTA, 'LEGENDARY': GOLD}

# Map color keys from engine to actual colors
KEY_TO_COLOR = {
    "WHITE": WHITE, "RED": RED, "GREEN": GREEN, "BLUE": BLUE, "YELLOW": YELLOW, "CYAN": CYAN, "MAGENTA": MAGENTA, "BLACK": BLACK,
    "ALLY_COLOR": ALLY_COLOR, "ENEMY_COLOR": ENEMY_COLOR,
    "DAMAGE_PHYSICAL_COLOR": DAMAGE_PHYSICAL_COLOR, "DAMAGE_MAGIC_COLOR": DAMAGE_MAGIC_COLOR, "DAMAGE_TRUE_COLOR": DAMAGE_TRUE_COLOR,
    "HEAL_COLOR": HEAL_COLOR, "BUFF_COLOR": BUFF_COLOR, "OVERTIME_COLOR": OVERTIME_COLOR,
     "HIT_FLASH_COLOR": HIT_FLASH_COLOR, "HEAL_FLASH_COLOR": HEAL_FLASH_COLOR, "CAST_FLASH_COLOR": CAST_FLASH_COLOR,
     "DEATH_COLOR": DEATH_COLOR, "PROJECTILE_BASIC_COLOR": PROJECTILE_BASIC_COLOR, "PROJECTILE_MAGIC_COLOR": PROJECTILE_MAGIC_COLOR,
     "SLASH_COLOR": SLASH_COLOR, "HIT_SPARK_COLOR": HIT_SPARK_COLOR,
}

# Layout
BENCH_SLOTS = 8
BENCH_Y = SCREEN_HEIGHT - 60
BENCH_X_START = 250
SLOT_SIZE = 50
SLOT_MARGIN = 10

BOARD_ROWS = 3
BOARD_COLS = 6
BOARD_X_START = (SCREEN_WIDTH - (BOARD_COLS * (SLOT_SIZE + SLOT_MARGIN))) // 2 + 50
BOARD_Y_START = SCREEN_HEIGHT - 280

SHOP_SLOTS = 5
SHOP_Y = 100
SHOP_X_START = 250

INFO_PANEL_X = 10
INFO_PANEL_Y = 10
SYNERGY_PANEL_X = 10
SYNERGY_PANEL_Y = 300
SYNERGY_LINE_HEIGHT = 18 

MAX_ITEMS_INVENTORY = 6
INVENTORY_X_START = SHOP_X_START
INVENTORY_Y = BOARD_Y_START - SLOT_SIZE - 20
ITEM_SLOT_SIZE = 30

BUTTON_HEIGHT = 40

COMBAT_ARENA_X = 220
COMBAT_ARENA_Y = 100
COMBAT_ARENA_WIDTH = SCREEN_WIDTH - 400
COMBAT_ARENA_HEIGHT = SCREEN_HEIGHT - 200
COMBAT_UNIT_RADIUS = 16 
ARENA_MIN_X = COMBAT_ARENA_X + COMBAT_UNIT_RADIUS
ARENA_MAX_X = COMBAT_ARENA_X + COMBAT_ARENA_WIDTH - COMBAT_UNIT_RADIUS
ARENA_MIN_Y = COMBAT_ARENA_Y + COMBAT_UNIT_RADIUS
ARENA_MAX_Y = COMBAT_ARENA_Y + COMBAT_ARENA_HEIGHT - COMBAT_UNIT_RADIUS

MAP_X_START = 50
MAP_Y_START = 100
MAP_WIDTH = SCREEN_WIDTH - 100
MAP_HEIGHT = SCREEN_HEIGHT - 200
MAP_NODE_RADIUS = 15

EVENT_CHOICE_WIDTH = 500
EVENT_CHOICE_HEIGHT = 300
EVENT_CHOICE_RECT = pg.Rect(SCREEN_WIDTH // 2 - EVENT_CHOICE_WIDTH // 2, 
                                SCREEN_HEIGHT // 2 - EVENT_CHOICE_HEIGHT// 2, 
                                EVENT_CHOICE_WIDTH, EVENT_CHOICE_HEIGHT)
EVENT_BUTTON_WIDTH = 400
EVENT_BUTTON_HEIGHT = 60
# ------------------------------------------------------------------ #
#  Adaptive scaling
# ------------------------------------------------------------------ #
DESIGN_HEIGHT = 900          # logical reference canvas (16:9)
_pg_info = pg.display.Info() # valid only *after* pg.init()!
SCREEN_HEIGHT = _pg_info.current_h if _pg_info.current_h else 900
# 1 × on a 900‑px tall screen, 2 × on 1800 px, etc. (rounded .25 steps)
SCALE = round(max(.75, SCREEN_HEIGHT / DESIGN_HEIGHT) * 4) / 4

# ------------------------------------------------------------------ #
#  Colours
# ------------------------------------------------------------------ #
def _c(r, g, b): return pg.Color(r, g, b)
WHITE,  BLACK   = _c(250,250,250), _c(10, 10, 10)
GREY,   DGREY   = _c(170,170,170), _c(40, 40, 40)
GOLD,   RED     = _c(238,176, 34), _c(208, 50, 50)
GREEN,  BLUE    = _c( 88,200, 70), _c( 80,160,255)
BG        = _c(22,24,28)
PANEL_BG  = _c(34,38,44)
GRID_LINE = _c(70,75,85)

RARITY_COL = [GREY, GREEN, BLUE, GOLD, RED]  # 0‑4 stars

# ------------------------------------------------------------------ #
#  Layout (logical units)
# ------------------------------------------------------------------ #
BAR_H          = 14
STATUS_W       = 280
SHOP_H         = 160
BENCH_H        = 110
SYNERGY_W      = 240
PADDING        = 8
ICON           = 24
FONT_S         = 18
TINY_FONT_S    = 14
# Animation Durations (imported from data for lerping)
ANIM_DURATIONS = {
     'ATTACKING': ATTACK_ANIM_DURATION,
     'HIT': HIT_ANIM_DURATION,
     'HEALED': HEAL_ANIM_DURATION,
     'CASTING': CAST_ANIM_DURATION,
     'DYING': DEATH_ANIM_DURATION
}
